### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by v-Kaefer** [Benfato/GCS-T1-2024-2#1]
# Lista de Tarefas com as Atividades do Trabalho

Cada time deverá:
- [ ] 1. Cada grupo deve criar um único repositório no GitHub.
- [ ] 2. Definir e descrever claramente o seu processo de branching (fluxo de trabalho), com base em
um dos fluxos estudados.
- [ ] 3. Descrever as regras do fluxo de trabalho no relatório e segui-las ao longo da implementação.
- [ ] 4. Escrever o software a partir do repositório inicial criado de acordo com os requisitos e com o
fluxo de trabalho definido pelo time.
- [ ] 5. Entregar um relatório via Moodle até a data limite.

Apenas clicando em uma das atividades, você será direcionado para determinada _issue_, com suas subtarefas. Ao finalizar/realizar a tarefa, basta fechar a _issue_, para que determinada tarefa conste como concluída.
